---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nomachine 
  labels:
    type: nomachine
spec:
  replicas: 3
  template:
    metadata:
      labels:
         type: nomachine 
    spec:
       containers:
       - name: nomachine 
         image: purushothamkdr453/nomachine:latest 
         ports:
         - containerPort: 4000
         resources:
           limits:
             nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: nomachine-svc 
spec:
  type: LoadBalancer
  selector:
    type: nomachine
  ports:
    - protocol: TCP
      port: 4000 
      targetPort: 4000 
